#!name=X 广告与遥测复写
#!desc=X 广告与遥测复写 解决发热与电量消耗
#!homepage=https://github.com/jik1818/Proxy-Rules
#!author=jik1818
#!icon=https://raw.githubusercontent.com/luestr/IconCenter/master/Apps/X.png

[Rewrite]
^https?:\/\/analytics\.twitter\.com reject-200
^https?:\/\/ads-api\.twitter\.com\/.* reject-200
^https?:\/\/.*\.pixelscan\.net\/.* reject-200
^https?:\/\/crashlyticsreports-pa\.googleapis\.com\/.* reject-200
^https?:\/\/firebase-settings\.crashlytics\.com\/.* reject-200
^https?:\/\/firebaselogging-pa\.googleapis\.com\/.* reject-200
^https?:\/\/app-analytics-services\.com\/.* reject-200
^https?:\/\/.*\.doubleclick\.net\/.* reject-200
^https?:\/\/.*\.sentry\.io\/.* reject-200
^https?:\/\/.*\.singular\.net\/.* reject-200
^https?:\/\/.*\.adnxs\.com\/.* reject-200
^https?:\/\/.*\.adjust\.com\/.* reject-200
^https?:\/\/.*\.adjust\.io\/.* reject-200
^https?:\/\/.*\.sprig\.com\/.* reject-200
^https?:\/\/ogads-pa\.clients6\.google\.com\/.* reject-200
^https?:\/\/www\.googletagmanager\.com\/.* reject-200
^https?:\/\/device-provisioning\.googleapis\.com\/.* reject-200


[MITM]
hostname = *.doubleclick.net, *.crashlytics.com, ads-api.twitter.com, app-analytics-services.com, analytics.twitter.com, *.pixelscan.net, firebaselogging-pa.googleapis.com, crashlyticsreports-pa.googleapis.com, *.sentry.io, *.singular.net, *.adnxs.com, *.adjust.com, *.adjust.io, *.sprig.com, ogads-pa.clients6.google.com, www.googletagmanager.com, device-provisioning.googleapis.com
