#!name=X 广告与遥测复写
#!desc=拦截 X 及其内置的第三方指纹追踪，解决发热与电量消耗。
#!homepage=https://github.com/jik1818/Proxy-Rules
#!author=jik1818
#!icon=https://raw.githubusercontent.com/luestr/IconCenter/master/Apps/X.png

[Rewrite]
^https?:\/\/analytics\.twitter\.com reject-dict
^https?:\/\/.*\.pixelscan\.net reject-dict
^https?:\/\/crashlyticsreports-pa\.googleapis\.com\/.* reject-dict
^https?:\/\/ads-api\.twitter\.com\/.* reject-dict
^https?:\/\/firebase-settings\.crashlytics\.com\/.* reject-dict
^https?:\/\/.*\.doubleclick\.net\/.* reject-dict
^https?:\/\/googleads\.g\.doubleclick\.net\/.* reject-dict
^https?:\/\/firebaselogging-pa\.googleapis\.com\/.* reject-dict
^https?:\/\/app-analytics-services\.com\/.* reject-dict

[MITM]
hostname = *.doubleclick.net, *.crashlytics.com, ads-api.twitter.com, app-analytics-services.com, firebaselogging-pa.googleapis.com, growth-pa.googleapis.com, clienttracing-pa.googleapis.com, ogads-pa.googleapis.com, crashlyticsreports-pa.googleapis.com, analytics.twitter.com, *.pixelscan.net

