#!name=阿里 & 腾讯 复写
#!desc=阿里 & 腾讯 复写 解决发热与电量消耗
#!homepage=https://github.com/jik1818/Proxy-Rules
#!author=jik1818
#!icon=https://raw.githubusercontent.com/luestr/IconCenter/master/Apps/Alipay.png

[Rewrite]
# --- 微信 ---
^https?:\/\/dns\.weixin\.qq\.com\.cn reject-dict

# --- 阿里系 ---
^https?:\/\/.*\.ynuf\.aliapp\.org reject-dict
^https?:\/\/ynuf\.aliapp\.org reject-dict
^https?:\/\/amdc\.alipay\.com reject-dict
^https?:\/\/h-adashx\.ut\.taobao\.com reject-dict
^https?:\/\/mum\.alibabachengdun\.(com|net) reject-dict
^https?:\/\/loggw-ex\.alipay\.com reject-dict
^https?:\/\/umdc\.alibabachengdun\.com reject-dict
^https?:\/\/sjarvis\.taobao\.com reject-dict
^https?:\/\/dualstack-logs\.amap\.com reject-dict
^https?:\/\/yixiu-abtest\.alicdn\.com reject-dict
^https?:\/\/.*\.mmstat\.com reject-dict
^https?:\/\/.*\.log\.aliyuncs\.com reject-dict
^https?:\/\/tracert\.alipay\.com reject-dict
^https?:\/\/audid-api\.taobao\.com reject-dict
^https?:\/\/logs\.amap\.com reject-dict
^https?:\/\/collect\.alipay\.com reject-dict
^https?:\/\/www\.qchannel01\.cn reject-dict
^https?:\/\/i\.qchannel03\.cn reject-dict
^https?:\/\/amdc\.m\.taobao\.com reject-dict
^https?:\/\/optimus-ads\.amap\.com reject-dict

# --- 百度 & 极光推送 ---
^https?:\/\/h2tcbox\.baidu\.com reject-dict
^https?:\/\/hm\.baidu\.com reject-dict
^https?:\/\/s\.bdstatic\.com reject-dict
^https?:\/\/.*\.jpush\.cn reject-dict
^https?:\/\/.*\.jpush\.io reject-dict
^https?:\/\/sp1\.baidu\.com reject-dict

[MITM]
hostname = sjarvis.taobao.com, *.sjarvis.taobao.com, amdc.alipay.com, cdn.ynuf.aliapp.org, ynuf.aliapp.org, *.ynuf.aliapp.org, h-adashx.ut.taobao.com, mum.alibabachengdun.com, mum.alibabachengdun.net, loggw-ex.alipay.com, umdc.alibabachengdun.com, dualstack-logs.amap.com, yixiu-abtest.alicdn.com, *.mmstat.com, *.log.aliyuncs.com, tracert.alipay.com, audid-api.taobao.com, logs.amap.com, collect.alipay.com, www.qchannel01.cn, i.qchannel03.cn, amdc.m.taobao.com, optimus-ads.amap.com, h2tcbox.baidu.com, hm.baidu.com, s.bdstatic.com, *.jpush.cn, *.jpush.io, sp1.baidu.com
