#!name=X 广告与遥测复写
#!desc=X 广告与遥测复写 解决发热与电量消耗
#!homepage=https://github.com/jik1818/Proxy-Rules
#!author=jik1818
#!icon=https://raw.githubusercontent.com/luestr/IconCenter/master/Apps/X.png

[Rewrite]
# Twitter / X 分析与广告
^https?:\/\/analytics\.twitter\.com reject-200
^https?:\/\/ads-api\.twitter\.com\/.* reject-200

# 指纹检测（pixelscan）
^https?:\/\/.*\.pixelscan\.net\/.* reject-200

# Google / Firebase / Crashlytics 遥测
^https?:\/\/crashlyticsreports-pa\.googleapis\.com\/.* reject-200
^https?:\/\/clienttracing-pa\.googleapis\.com\/.* reject-200
^https?:\/\/firebase-settings\.crashlytics\.com\/.* reject-200
^https?:\/\/firebaselogging-pa\.googleapis\.com\/.* reject-200
^https?:\/\/app-analytics-services\.com\/.* reject-200

# Google 广告网络
^https?:\/\/.*\.doubleclick\.net\/.* reject-200

# Sentry 遥测
^https?:\/\/.*\.sentry\.io\/.* reject-200

# Singular 遥测
^https?:\/\/.*\.singular\.net\/.* reject-200

# adnxs 广告网络
^https?:\/\/.*\.adnxs\.com\/.* reject-200

[MITM]
hostname = *.doubleclick.net, *.crashlytics.com, ads-api.twitter.com, app-analytics-services.com, analytics.twitter.com, *.pixelscan.net, firebaselogging-pa.googleapis.com, crashlyticsreports-pa.googleapis.com, clienttracing-pa.googleapis.com, *.sentry.io, *.singular.net, *.adnxs.com







