#!name=阿里系广告与遥测 MitM
#!desc=阿里系广告与遥测 MitM
#!homepage=https://github.com/jik1818/Proxy-Rules
#!author=jik1818
#!icon=



[MITM]
# 解密域名
hostname = sjarvis.taobao.com,*.sjarvis.taobao.com,amdc.alipay.com,cdn.ynuf.aliapp.org

















