#!name=阿里系廣告與遙測拦截
#!desc=阿里系流氓域名進行本地秒回防止發熱
#!icon=🛍️

[Rewrite]
^https?:\/\/cdn\.ynuf\.aliapp\.org reject-dict
^https?:\/\/amdc\.alipay\.com reject-dict
^https?:\/\/h-adashx\.ut\.taobao\.com reject-dict
^https?:\/\/mum\.alibabachengdun\.com reject-dict
^https?:\/\/loggw-ex\.alipay\.com reject-dict
^https?:\/\/umdc\.alibabachengdun\.com reject-dict
^https?:\/\/sjarvis\.taobao\.com reject-dict
^https?:\/\/dualstack-logs\.amap\.com reject-dict
^https?:\/\/yixiu-abtest\.alicdn\.com reject-dict

[MITM]
hostname = sjarvis.taobao.com, *.sjarvis.taobao.com, amdc.alipay.com, cdn.ynuf.aliapp.org, h-adashx.ut.taobao.com, mum.alibabachengdun.com, loggw-ex.alipay.com, umdc.alibabachengdun.com, dualstack-logs.amap.com, yixiu-abtest.alicdn.com


