#!name = YouTube 增強 & 去廣告
#!desc = 整合去廣告、字幕翻譯、界面按鈕屏蔽
#!icon = https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png

[Argument]
blockUpload = switch, true, tag=屏蔽上傳按鈕, desc=是否屏蔽上傳按鈕
blockImmersive = switch, true, tag=屏蔽選段按鈕, desc=是否屏蔽選段按鈕
blockShorts = switch, false, tag=屏蔽Shorts按鈕, desc=是否屏蔽Shorts按鈕
captionLang = input, "off", tag=字幕翻譯語言, desc=語言代碼遵循 Google Translate Languages Codes，填入 off 關閉翻譯
debug = switch, false, tag=啟用調試模式, desc=是否啟用調試模式輸出更多日誌

[Rule]
# 拦截YouTube QUIC (UDP 443)
AND,((DOMAIN-SUFFIX,youtube.com),(PROTOCOL,QUIC)),REJECT-DROP 
AND,((DOMAIN-SUFFIX,googlevideo.com),(PROTOCOL,QUIC)),REJECT-DROP 
AND,((DOMAIN-SUFFIX,ggpht.com),(PROTOCOL,QUIC)),REJECT-DROP 
AND,((DOMAIN-SUFFIX,ytimg.com),(PROTOCOL,QUIC)),REJECT-DROP 
AND,((DOMAIN-SUFFIX,gstatic.com),(PROTOCOL,QUIC)),REJECT-DROP 
AND,((DOMAIN-SUFFIX,googleusercontent.com),(PROTOCOL,QUIC)),REJECT-DROP 
AND,((DOMAIN-SUFFIX,suggestqueries.google.com),(PROTOCOL,QUIC)),REJECT-DROP

[Script]
# YouTube 界面與廣告處理響應腳本
http-response ^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch|log_event|config))(\?(.*))?$ script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js, requires-body=true, binary-body-mode=true, timeout=20, argument={"captionLang":"{captionLang}","blockUpload":{blockUpload},"blockImmersive":{blockImmersive},"blockShorts":{blockShorts},"debug":{debug}}, tag=YouTube增強-響應

# YouTube 請求初始化腳本
http-request ^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&ack.* script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.request.js, requires-body=true, binary-body-mode=true, argument={"captionLang":"{captionLang}"}, tag=YouTube增強-請求初始化

# YouTube 日誌腳本
http-request ^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/log_event script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.request.js, requires-body=true, binary-body-mode=true, tag=YouTube增強-日誌

[Rewrite]
# 廣告請求阻斷
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads reject
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) reject
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext reject
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad reject

# 畫質與重定向修正
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) header $1$2$3

[MITM]
hostname = *.googlevideo.com, youtubei.googleapis.com, www.youtube.com, s.youtube.com
