#!name=MITM
#!desc=MITM
#!homepage=https://github.com/jik1818/Proxy-Rules
#!author=jik1818
#!icon=

[MITM]
# 解密域名
hostname = *.doubleclick.net,*.crashlytics.com,ads-api.twitter.com,app-analytics-services.com,firebaselogging-pa.googleapis.com








