#!name = YouTube 增強 & 去廣告
#!desc = 整合去廣告、字幕翻譯、界面按鈕屏蔽
#!icon = https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png

[Rule]
# 拦截 YouTube QUIC
AND,((DOMAIN-SUFFIX,youtube.com),(PROTOCOL,QUIC)),REJECT-DROP
AND,((DOMAIN-SUFFIX,googlevideo.com),(PROTOCOL,QUIC)),REJECT-DROP
AND,((DOMAIN-SUFFIX,ggpht.com),(PROTOCOL,QUIC)),REJECT-DROP
AND,((DOMAIN-SUFFIX,ytimg.com),(PROTOCOL,QUIC)),REJECT-DROP
AND,((DOMAIN-SUFFIX,gstatic.com),(PROTOCOL,QUIC)),REJECT-DROP
AND,((DOMAIN-SUFFIX,googleusercontent.com),(PROTOCOL,QUIC)),REJECT-DROP
AND,((DOMAIN-SUFFIX,suggestqueries.google.com),(PROTOCOL,QUIC)),REJECT-DROP

[Script]
# YouTube 界面與廣告處理響應腳本
http-response ^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch|log_event|config))(\?(.*))?$ \
script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js, requires-body=true, binary-body-mode=true, timeout=20

# YouTube 請求初始化腳本
http-request ^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&ack.* \
script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.request.js, requires-body=true, binary-body-mode=true

# YouTube 日誌腳本
http-request ^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/log_event \
script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.request.js, requires-body=true, binary-body-mode=true

[Rewrite]
# 廣告請求阻斷
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads reject
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) reject
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext reject
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad reject

# 畫質與重定向修正
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) header $1$2$3

[MITM]
hostname = *.googlevideo.com, youtubei.googleapis.com, www.youtube.com, s.youtube.com
